### ISSUE TITLE
BiocCheck

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaSim#10]
Running `BiocCheck::BiocCheck()` gives the following. Most can be fixed (see notes below).

[2] "The Description field in the DESCRIPTION is made up by less than 3\nsentences. Please consider expanding this field, and structure it as a\nfull paragraph"                        

-> Just expand a bit.

[3] " 'sessionInfo' not found in vignette(s)"                                                                                                                                           

-> Add this in the end of vignette (see examples from **mia**)

[4] " Avoid sapply(); use vapply()"                                      

-> If it is easy to replace sapply with vapply then this should be done.

                                                                                                            
[5] " Avoid 1:...; use seq_len() or seq_along()"                                                                                                                                        

-> Change everywhere

[6] "Recommended function length <= 50 lines."                                                                                                                                         

-> Change where possible, not critical if few lines remain too long
 
[7] "Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements."         

-> Good to add (see other pkgs for an exmple). Can be just one message: "- First package version ready"
                                                                
[8] "Consider adding unit tests. We strongly encourage them. See\n  http://bioconductor.org/developers/how-to/unitTesting-guidelines/."                                                 

-> See the other issue on this.

[9] "Cannot determine whether maintainer is subscribed to the bioc-devel\nmailing list (requires admin credentials).  Subscribe here:\nhttps://stat.ethz.ch/mailman/listinfo/bioc-devel"

-> Subscribe in the given URL

**Comment by YagmurSimsekk** [comment]
[4]I tried changing sapply() to vapply() but it didn't work successfully. vapply() requires FUN.VALUE and i couldn't receive the same values as i would receive with sapply(). So it decided to try it later again. 

[6] Two functions are longer than 50. One of them has 114 and the other 69. So it wasn't possible to bring it down to 50.

[9] Even though, i subscribed, it still gives me the same note.

**Comment by antagomir** [comment]
The `vapply` should just show an example output that is in the desired format, e.g.
`vapply(x, kurtosis, 1)` or `vapply(x, as.character, "char")` or `vapply(1:3, function (x) {x^2}, 1)` or `vapply(1:3, function (x) {c(x, x^2)}, c(1,2))` etc. Let us aim to get this fixed.

Few too long functions ok. This always happens.

Subscription issue ok for now.

**Comment by FelixErnst** [comment]
Have a look at `?vapply` or search code for other `vapply` instances.

`vapply(list, FUN, character(1))` means that each call to `FUN` with every element in the `list` must return a character value of length 1. You can als specify `numeric`, `integer` or `logical`

**Comment by YagmurSimsekk** [comment]
@FelixErnst For `powerlawA` function [here](https://github.com/microbiome/miaSim/blob/main/R/simulateGLV.R) changing to `vapply (seq_len(n), FUN = ... , numeric(1)) ` gives different matrix in the end than the one I could get with sapply. So i am assuming that it is a wrong way to do it if it is not the same matrix in the end. But `integer` and `logical` are not applicable as well and if I run the function steps one by one H and h needs to be in numeric format.

**Comment by antagomir** [comment]
Can you show here the case that you have with sapply, or point to the correct position in the code so we can propose a solution?

**Comment by YagmurSimsekk** [comment]
[H](https://github.com/microbiome/miaSim/blob/a57f83cd1adb1589750dac4e703af71c737e667d/R/simulateGLV.R#L71) and [h](https://github.com/microbiome/miaSim/blob/a57f83cd1adb1589750dac4e703af71c737e667d/R/simulateGLV.R#L77) both can be written with` vapply(seq_len(n), FUN = ... , numeric(1)) ` and but when i apply `powerlawA(n = 4, alpha = 2)` it gives me a different matrix than the one i get when i use `sapply(seq_len(n), FUN = ...)` .

**Comment by YagmurSimsekk** [comment]
Sorry, I just realized that the matrix created by powerlawA function changes every time even if the parameters n and alpha are the same. So then maybe numeric(1) is correct to apply ?

**Comment by antagomir** [comment]
The contents of the matrix are stochastic but I assume that the output should be always in the same format and dimension?

What is the full command sequence that you are using with sapply? Can you provide a (reproducible?) example

**Comment by YagmurSimsekk** [comment]
Yes the dimension and format of the output is the same every time just the numbers `H <- vapply(seq_len(n), FUN = function(i){
        1 + ((pl[i]-min(pl))/(max(pl)-min(pl)))
    }, as.matrix(1,n))`

**Comment by YagmurSimsekk** [comment]
Yes the dimension and format of the output is the same every time. With sapply, [H](https://github.com/microbiome/miaSim/blob/a57f83cd1adb1589750dac4e703af71c737e667d/R/simulateGLV.R#L71) would be  `H <- sapply(seq_len(n), FUN = function(i){ 1 + ((pl[i]-min(pl))/(max(pl)-min(pl))) })`  for [h](https://github.com/microbiome/miaSim/blob/a57f83cd1adb1589750dac4e703af71c737e667d/R/simulateGLV.R#L77) `h <- sapply(seq_len(n), FUN = function(i){
        min(
            ceiling(d*pl[i]/mean(pl)),
            n
        )
    })`

**Comment by YagmurSimsekk** [comment]
And` A = powerlawA(n = 4, alpha = 2)` gives matrix [1:4, 1:4] with changing numbers

**Comment by FelixErnst** [comment]
Just to provide a bit more information on the fact, that `sapply` if not really a good choice. Depending on the output of each function call `sapply` tries to simplify the data, which mean sometimes returning a matrix and sometime returning a vector or a list. From a programmers point of view, this is not good, since you cannot be sure about the type of data for subsequent functions, which either you miss and have weird error messages and bug reports or you end up with a lot ifs after the `sapply`.

`vapply` on the other hand is the very tidy. You get what you ask for and if data and function don't return what you ask for, `vapply` thors an error. With this it is very easy to catch bugs and to avoid them in the first place. If you cannot use `vapply`, use `lapply` and simplify the data yourself. This way you are in control and can avoid bugs from the start.

And then there is the kicker: 
> We recommend that vapply() be used instead of sapply(). Problems arise when the X argument to sapply() has length 0; the return type is then a list() rather than a vector or array. (NOTE)

So it is basically the same situation, why you don't use `1:n` but `seq_len(n)`

**Comment by YagmurSimsekk** [comment]
Thank you for the explanation! That's pretty understandable. I was trying to get exactly the same matrix in the end of the function by both using sapply and vapply but it turned out that the values of the matrix can change every time even with the same parameters. So i can use `FUN.VALUE = numeric(1)` with vapply since we want to get numeric value in the end of the vapply functions
