### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaSim#11]
Running 

`devtools::run_examples()`

Gives the following error

> ### Name: simulateGLV
> ### Title: simulateGLV
> ### Aliases: simulateGLV
> 
> ### ** Examples
> 
> row_data <- data.frame(Kingdom = "A",
+                     Phylum = rep(c("B1", "B2"), c(500, 500)),
+                     Class = rep(c("C1", "C2"), each = 500),
+                     ASV = paste0("D", seq_len(1000)),
+                     row.names = rownames(paste0("species", seq_len(1000))),
+                     stringsAsFactors = FALSE)

>                     row_data <- t(row_data)

> col_data <- data.frame(sampleID = seq_len(1000),
+                     time = as.Date(sample(as.numeric(as.Date('2000-01-01')):
+                                 as.numeric(as.Date('2014-01-01')), 1000,
+                                             replace = TRUE),
+                                                     origin = '1970-01-01'),
+                     row.names = colnames(paste0("sample", seq_len(1000))),
+                     stringsAsFactors = FALSE)

> simulateGLV(N = 4, A = powerlawA(n = 4, alpha = 2), tend = 1000)
Error in is(colData, "DataFrame") : object 'col_data' not found
ℹ Loading miaSim

**Comment by YagmurSimsekk** [comment]
Oh i wasn't checking with run_examples. I will check it now
