### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by FelixErnst** [microbiome/miaSim#24]
Hi,

I have read through of the PRs and the code in general and I want to offer some advice.

1. Avoid for loops.
 I have seen `for(i in 1:n)` a number of times. There are two issues with that. First the use of the `for` loop instead of lapply, second the use of `1:n` instead of `seq_len()`. The first is a choice, the second is a dealbreaker during bioconductor submission. The second one can be easily fixed and the first one requires some thinking, but will lead in 100% of case to better code and better readability of the code. Hint: You cannot write a specific unit test for the code in the `for` loop.

2. Nested functions
Nesting a named function inside another S3 or S4 method is just bad. You cannot unit test it and you cannot reuse it.

3. Inconsistent naming of functions
Sometimes camelCase, somtimes underscored, sometimes descriptive, sometimes not... I could go on. Applies also partially to naming of variables. Have fun remembering the meaning of a variable in 6 weeks, 6 months and 6 years.

4. Inputs not checked for validity
Good luck with providing user support. You will go bonkers if the package is used by a large audience. Do not trust any variable until checked for validity, otherwise you will chase your tail during debugging and answering issues.

5. Inconsistent indentation
Reading the code as the one who didn't write it without consistent indentation and positioning of `{}` is a nightmare.

You can totally disregard any of this, but in my experience all thes points will help you with:
- Bioconductor submission
- maintainability
- Maturing of the package over time by offering clean code for interfacing for other developers

Felix

**Comment by antagomir** [comment]
Thanks a lot @FelixErnst 

I agree with all points we have been discussing this last week with the contributors. There is a learning curve that some contributors are going through now. This will be hopefully improved soon. 

For point 4, you can also check for examples from **mia**.

@YagmurSimsekk can coordinate so that these get fixed and we chat more as needed.

**Comment by YagmurSimsekk** [comment]
Thank you for your comments!

We are getting more familiar with styling and adjusting into Bioconductor requirements. In the latest version , we cleared all `1:n`  and some for loops. Since we had limited time for Bioconductor submission and our contributors who are more familiar with the code/owners of the code joined us pretty recently.

**Comment by antagomir** [comment]
The 1:n and other such changes need to be brought to the bioc submission branch asap. New functionality can wait more.

**Comment by YagmurSimsekk** [comment]
Thank you for your comments!

We are becoming more and more familiar with styling and adapting to Bioconductor requirements. In the latest version we cleared all '1:n' and some for loops. Our contributors who are more familiar with the codes have joined us quite recently.

**Comment by YagmurSimsekk** [comment]
@antagomir It was already submitted with the latest version. There is nothing new to change

**Comment by FelixErnst** [comment]
The bioc submission branch is `main` or `master`, so I guess I wouldn't use a seperate bioc submission branch.

Regarding nested functions:
`logistic.model` is still a nested function. `.logistic.model` would be the approproate name next to the S4 function. `tDyn` is a non-sensical name and without special knowledge you don't know what it is about. `simulateTimeSeries` would be probaly a good name, wouldn't it?

**Comment by antagomir** [comment]
There is no separate bioc submission branch. We are using main/master as the submission branch.. I was using confusing language.

**Comment by YagmurSimsekk** [comment]
We are not planning to add logisticmodel function for this bioconductor submission, so we will work on it more.  Also as far as i understood, `.`  shouldn't be used for function names. [Function names should be camel case or utilize the underscore _ and not have a dot . which indicates S3 dispatch.](https://www.bioconductor.org/developers/package-guidelines/#rcode)

**Comment by FelixErnst** [comment]
> `.` shouldn't be used for function names as it is written on the page

`.some_function_name` cannot be S3 dispatch.
`as.data.frame.assay` is S3 diaptch. Trick question; Which dot is for the dispatch?

So I think this a non issue, is it? You can have a look at the code in `mia` and count the functions starting with a dot... There are many and this is just fine

**Comment by antagomir** [comment]
@YagmurSimsekk / @gaoyu19920914 could you check if there is something here to add still? If there are multiple notable points it might be good to open separate issue for each distinct suggestion. If all relevant points have now been taken into account sufficiently this could be closed.

Or we can discuss here / Bioc meeting if you can check and summarize where we are with this issue.

**Comment by YagmurSimsekk** [comment]
I think we changed the functions as it was suggested and now following the suggestions with new functions. We can close this.
