### ISSUE TITLE
Parameters as the field of SE object 

### ISSUE THREAD

**Issue by YagmurSimsekk** [microbiome/miaSim#25]
Hi, 

We have been thinking on the topic of adding parameters as the fields of SE object. Since some parameters are generated by distribution functions(mostly uniform distribution for instance in [simulateGLV function](https://github.com/microbiome/miaSim/blob/main/R/simulateGLV.R) ), adding them as fields would be one way of seeing them explicitly, so the users can see that they are working on. But we are not sure how suitable it is for SE object structure or whether it is outside the concept of SE object class.

Any opinion on this is appreciated.

**Comment by antagomir** [comment]
This now seems to be solved as the parameters are stored in the metadata slot in the examples.

@YagmurSimsekk and others - kindly close the issues as they become ready. Or is there still something pending on this one? Correct me if I am mistaken, closing this now.
