### ISSUE TITLE
Activate vignette examples? 

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaSim#30]
All or most vignette material is now with `eval=FALSE`. Can it be changed into `eval=TRUE`?

**Comment by antagomir** [comment]
@gaoyu19920914 / @YagmurSimsekk / @danielriosgarza any comment on this?

**Comment by YagmurSimsekk** [comment]
I guess it was fixed a while ago. There are only two `eval=FALSE` chunks, and they are both BiocManager installation chunks, which shouldn't be running.

**Comment by antagomir** [comment]
Perfect. Then closing this issue.

Feel free to close issues after they are completed. Otherwise we must always assume they are still pending.
