### ISSUE TITLE
Automated GHA checks are not run

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaSim#36]
This should be configured.

The .github/workflows/ file is there and all seems like in mia and other packages. But the runs do not activate with PRs, unlike in the other packages.

Some leads might be [here](https://orchid00.github.io/actions_sandbox/).

Solve and also report the solution here.

**Comment by antagomir** [comment]
This also seems to concern automated website updates which explains issue

**Comment by antagomir** [comment]
@YagmurSimsekk any chance to give it a try?

**Comment by YagmurSimsekk** [comment]
It seems to be in sync with the main branch, at least the functions are.

**Comment by antagomir** [comment]
Ah it seems that .github/workflows is missing from main branch. This may explain. I will add it now.

**Comment by antagomir** [comment]
Not working, see PR #39

**Comment by antagomir** [comment]
Ok solved by #39 now
