### ISSUE TITLE
estimateAFromSimulations examples

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaSim#60]
The function `estimateAFromSimulations` is essential.

Therefore it should be clearly shown in some appropriate function manpage (roxygen documentation) example how to use this, and/or in the vignette.

**Comment by gaoyu19920914** [comment]
This was done [here](https://github.com/microbiome/miaSim/blob/b98c15dc74b50aebaa81267a33fe20cc3ab79185/R/utils.R#L313) previously. Now that the data container is changed, and I will work on it soon.

**Comment by antagomir** [comment]
Ok great.

As far as I can see, no changes to the function `estimateAFromSimulations` are needed because it is not representing community data. 

However if this function has changed in some way, open the PR so that we can take it now into account in any subsequent development.

**Comment by gaoyu19920914** [comment]
OK! 

I confirm that the function `estimateAFromSimulations` takes lists of simulations (generated by `generateSimulations`) as input, and treat the lists of simulations only with `getCommunity`.

Therefore, it's true that there's nothing to change to this function as long as the `generateSimulations` and `getCommunity` works well with the TreeSE data.

**Comment by antagomir** [comment]
These were removed in the latest PR, I just noticed.

I have now added this back in PR #63 that is pending automated checks.

Some updates were necessary, it will be essential to check afterwards that the outputs are as expected.
