### ISSUE TITLE
getCommunity

### ISSUE THREAD

**Issue by pgallins** [microbiome/miaSim#67]
Hello. I am trying to run the caseStudy3-EnvironmentalComplexity.R code. I get this error:
Error in getCommunity(CRMtest) : could not find function "getCommunity"

**Comment by antagomir** [comment]
Which version of the package you have?

**Comment by pgallins** [comment]
miaSim 1.5.3 on R 4.3.0

**Comment by antagomir** [comment]
Ok fixed. We are in a process of updating and polishing the vignettes, and had overlooked this deprecated function.
