### ISSUE TITLE
Input a custom matrix A to use the function simulationGLV

### ISSUE THREAD

**Issue by chibaoshuijiao** [microbiome/miaSim#73]
I am tring to use the function simlationGLV by inputing a custom matrix A. But it doesn't seem to work well, and the generated timing data will contain nan values during the simulation. Are there any restrictions on the matrix A？

**Comment by danielriosgarza** [comment]
This would happen if you have a numerical explosion in one or more of the variables (i.e. the system you are trying to simulate is not stable). The solution would depend on the size and numerical range of your matrix. 

I would have to see your matrix to suggest ideas to solve your specific case, but this is not a malfunctioning of miaSim but rather a feature of the GLV model.

**Comment by chibaoshuijiao** [comment]
Thank you for your reply, I have no more questions for now
