### ISSUE TITLE
Check errors

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaSim#8]
`devtools::check()` gives the following NOTEs. To be fixed. 
 
Most or all function issues can be fixed by importing the mentioned functions.  

Most or all global variable issues can be fixed by initializing the variable names in the beginning of the funcrtion (i.e. `col_data <- NULL`). Or perhaps there is a better way to solve this?

 checking R code for possible problems ... NOTE
  powerlawA: no visible global function definition for ‘rnorm’
  simulateGLV,numeric: no visible binding for global variable ‘col_data’
  simulateGLV,numeric: no visible binding for global variable ‘row_data’
  simulateHubbell,numeric: no visible global function definition for
    ‘rmultinom’
  simulateHubbell,numeric: no visible global function definition for
    ‘rbinom’
  simulateSOI,numeric: no visible global function definition for ‘rgamma’
  simulateSOI,numeric: no visible global function definition for
    ‘rmultinom’
  Undefined global functions or variables:
    col_data rbinom rgamma rmultinom rnorm row_data
  Consider adding
    importFrom("stats", "rbinom", "rgamma", "rmultinom", "rnorm")
  to your NAMESPACE file.

**Comment by YagmurSimsekk** [comment]
I could remove global function definition notes with just adding the function with @importFrom but col_data and row_data didn't work with <- NULL comment. I tried to use globalVariables(c("row_data", "col_data")) . That worked but for some reason, it automatically deleted related .Rd file. So i decided to do take row_data and col_data out from examples and generalized it. Should i make new PR for that ?

**Comment by antagomir** [comment]
I think this is not related to @examples. Instead, it seems related to `simulateGLV` [lines 126-127](https://github.com/microbiome/miaSim/blob/main/R/simulateGLV.R). There, we have `row_data` and `col_data` called within the function. However, these have not been defined anywhere in the function.


These can be initialized as NULL in the beginning of the function (beginning meaning within the function, not in roxygen). But if these are not necessary nor modified later in the function, they can be entirely removed from the `SummarizedExperiment` call, just keeping the counts.
